services:
  mysql:
    image: mysql:8.0
    container_name: secureshop-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: secureshop
      MYSQL_USER: secureshop_user
      MYSQL_PASSWORD: secureshop_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3310:3306"
    volumes:
      - secureshop_mysql_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci

volumes:
  secureshop_mysql_data:
